//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssignment.Infrastructure.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindContext : DbContext
    {
        public NorthwindContext()
            : base("name=NorthwindContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<EmployeeSales> GetEmployeeSalesInfo(Nullable<int> startIdx, Nullable<int> endIdx, string name)
        {
            var startIdxParameter = startIdx.HasValue ?
                new ObjectParameter("StartIdx", startIdx) :
                new ObjectParameter("StartIdx", typeof(int));
    
            var endIdxParameter = endIdx.HasValue ?
                new ObjectParameter("EndIdx", endIdx) :
                new ObjectParameter("EndIdx", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSales>("GetEmployeeSalesInfo", startIdxParameter, endIdxParameter, nameParameter);
        }
    }
}
